name: website

on:
  push:
    branches:
    - "main"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      # Build and deploy the site to GitHub Pages
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: build Docker image
      uses: docker build  -t ${{ secrets.DOCKERHUB_USERNAME }}/box-website:latest .

    - name: Publish to GitHub Container Registry (GHR)
      uses: docker push ${{ secrets.DOCKERHUB_USERNAME }}/box-website:latest
